# Website details
name: "playwings dev blog"
description: ""
email: ""
author: ""
lang: "korean"
locale: "ko/KR"

# Jekyll
paginate: 10
highlighter: ""
markdown: kramdown
gems: [jekyll-paginate]
timezone: Asia/Seoul
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title
baseurl: http://playwings.github.io

# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

#Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
    include_posts:
        - "/index.html"
    change_frequency_name: "daily"
    priority_name: "1.00"